`define CLK_PERIOD 10
`define MAX_WAIT_FOR_READ_ENB 30

typedef enum bit [1:0] {NONE, HEADER_BYTE, PAYLOAD_DATA_BYTE, PARITY_BYTE} transaction_type_e;

typedef enum bit [2:0] {DECODE_ADDRESS, LOAD_FIRST_DATA, LOAD_DATA, LOAD_PARITY, FIFO_FULL_STATE, LOAD_AFTER_FULL, WAIT_TILL_EMPTY, CHECK_PARITY_ERROR} fsm_state_e;